# Generated by Django 4.2.6 on 2023-10-18 16:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertTop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_alert', models.ImageField(blank=True, null=True, upload_to='alert_image', verbose_name='عکس پیغام')),
                ('title_alert', models.CharField(max_length=200, verbose_name='عنوان پیغام')),
                ('slug_alert', models.SlugField(max_length=100, unique=True, verbose_name='آدرس پیغام')),
                ('description_alert', models.TextField(verbose_name='توضیح کوتاه')),
                ('publish_alert', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار پیغام')),
                ('created_alert', models.DateTimeField(auto_now_add=True, verbose_name='پیغام کی ایجاد شد؟')),
                ('updated_alert', models.DateTimeField(auto_now=True, verbose_name='پیغام کی آپدیت شد؟')),
                ('status_alert', models.CharField(choices=[('d', 'پیش نویس'), ('p', 'منتشر'), ('f', 'پیغام فاقد محتوا'), ('n', 'حذف خواهد شد'), ('b', 'به زودی منتشر خواهد شد'), ('r', 'به دلیل عمل نکردن به قوانین سایت رد شد')], default='d', max_length=1, verbose_name='  وضعیت انتشار پیغام')),
                ('Alert_type_alert', models.CharField(choices=[('نوع پیغام', (('hhh', 'هشدار'), ('sss', 'مهم'), ('aaa', 'پیغام تعمیر'), ('qqq', 'پیغام اضافه شدن ویژگی جدید'), ('www', 'پیغام تخفیف ویژه'), ('eee', 'پیغام کمک'), ('rrr', 'پیغام اطلاع رسانی'), ('ttt', 'پیغام انگیزشی'), ('yyy', 'پیغام تبلیغاتی'), ('uuu', 'پیغام ارتباط با ما'), ('iii', 'پیغام تبریک'), ('ooo', ' سایر ')))], max_length=3, verbose_name=' نوع پیغام')),
                ('Emphasis_on_the_message_alert', models.BooleanField(default=False, verbose_name='تاکید به پیغام')),
                ('category_alert', models.ManyToManyField(related_name='alerts', to='Articles.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'پیغام',
                'verbose_name_plural': 'پیغام ها',
            },
        ),
    ]
