# Generated by Django 4.2.6 on 2023-10-18 16:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0002_alerttop'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderTop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_alert', models.ImageField(upload_to='Slieder_image', verbose_name='عکس اسلاید')),
                ('title_Sliedr', models.CharField(max_length=200, verbose_name='عنوان اسلاید')),
                ('slug_Sliedr', models.SlugField(max_length=100, unique=True, verbose_name='آدرس اسلاید')),
                ('description_Sliedr', models.TextField(verbose_name='توضیح کوتاه')),
                ('publish_Sliedr', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار اسلاید')),
                ('created_Sliedr', models.DateTimeField(auto_now_add=True, verbose_name='اسلاید کی ایجاد شد؟')),
                ('updated_Sliedr', models.DateTimeField(auto_now=True, verbose_name='اسلاید کی آپدیت شد؟')),
                ('status_Sliedr', models.CharField(choices=[('d', 'پیش نویس'), ('p', 'منتشر'), ('f', 'اسلاید فاقد محتوا'), ('n', 'حذف خواهد شد'), ('b', 'به زودی منتشر خواهد شد'), ('r', 'به دلیل عمل نکردن به قوانین سایت رد شد')], default='d', max_length=1, verbose_name='  وضعیت انتشار اسلاید')),
                ('Sliedr_type_Sliedr', models.CharField(choices=[('نوع اسلاید', (('qwe', 'تبلیغاتی'), ('qwr', 'آموزشی'), ('qwt', 'مقاله برتر'), ('qwy', 'معرفی کتاب'), ('qwu', 'معرفی موضوع هفته'), ('qwi', 'جملات انگیزشی'), ('qwo', 'معرفی شخص')))], max_length=3, verbose_name=' نوع اسلاید')),
                ('Emphasis_on_the_message_Sliedr', models.BooleanField(default=False, verbose_name='تاکید به اسلاید')),
                ('category_Sliedr', models.ManyToManyField(related_name='Sliedrs', to='Articles.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'اسلاید',
                'verbose_name_plural': 'اسلاید ها',
            },
        ),
    ]
