# Generated by Django 4.2.6 on 2023-10-18 16:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0003_slidertop'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_Article', models.ImageField(upload_to='Articles_image', verbose_name='عکس مقاله')),
                ('File_Article', models.FileField(upload_to='Articles_file', verbose_name='فایل مقاله')),
                ('title_Article', models.CharField(max_length=200, verbose_name='نام مقاله')),
                ('slug_Article', models.SlugField(max_length=100, unique=True, verbose_name='آدرس مقاله')),
                ('Abstract_Article', models.TextField(verbose_name='چکیده')),
                ('Key_word_Article', models.CharField(max_length=200, verbose_name='کلید واژه')),
                ('Introduction_Article', models.TextField(verbose_name='مقدمه')),
                ('Body_or_text_Article', models.TextField(verbose_name='بدنه یا متن')),
                ('Result_Article', models.TextField(verbose_name='نتیجه')),
                ('References_Article', models.CharField(max_length=200, verbose_name='منابع و ماخذ')),
                ('publish_Article', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار مقاله')),
                ('created_Article', models.DateTimeField(auto_now_add=True, verbose_name='مقاله کی ایجاد شد؟')),
                ('updated_Article', models.DateTimeField(auto_now=True, verbose_name='مقاله کی آپدیت شد؟')),
                ('status_Article', models.CharField(choices=[('d', 'پیش نویس'), ('p', 'منتشر'), ('m', 'تعداد مقاله محدود'), ('f', 'مقاله موجود نیست'), ('n', 'حذف خواهد شد'), ('b', 'به زودی موجود خواهد شد'), ('r', 'به دلیل عمل نکردن به قوانین سایت رد شد')], default='d', max_length=1, verbose_name='  وضعیت انتشار مقاله')),
                ('Article_type_Article', models.CharField(choices=[('نوع مقاله', (('sar', 'سایر'), ('dns', 'دانشجویی'), ('ora', 'مقاله پژوهشی'), ('taa', 'مقاله نظری'), ('dor', 'روش تحقیق'), ('brr', 'نقد کتاب'), ('isi', 'مقالات ISI'), ('isc', 'مقالات ISC'), ('ara', 'مقالات مروری'), ('dst', 'نوشته روزانه'), ('cof', 'مقالات کنفرانسی'), ('scs', 'مقالات اسکوپوس'), ('rso', 'گزارش\u200cها و مطالعه مشاهدات'), ('ass', 'گزارش\u200cها یا نامه\u200cهای کوتاه')))], max_length=3, verbose_name=' نوع مقاله')),
                ('is_sale_Article', models.BooleanField(default=False, verbose_name='تخفیف ویژه')),
                ('category_Article', models.ManyToManyField(related_name='articls', to='Articles.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقاله ها',
            },
        ),
    ]
