# Generated by Django 4.2.6 on 2023-10-28 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Articles', '0004_articlesmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alerttop',
            options={'ordering': ['-publish_alert'], 'verbose_name': 'پیغام', 'verbose_name_plural': 'پیغام ها'},
        ),
        migrations.AlterModelOptions(
            name='articlesmodel',
            options={'ordering': ['-publish_Article'], 'verbose_name': 'مقاله', 'verbose_name_plural': 'مقاله ها'},
        ),
        migrations.AlterModelOptions(
            name='slidertop',
            options={'ordering': ['publish_Sliedr'], 'verbose_name': 'اسلاید', 'verbose_name_plural': 'اسلاید ها'},
        ),
        migrations.AddField(
            model_name='articlesmodel',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articls', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده'),
        ),
    ]
