# Generated by Django 4.2.6 on 2023-11-03 18:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0005_alter_alerttop_options_alter_articlesmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesmodel',
            name='Body_or_text_Article',
            field=ckeditor.fields.RichTextField(verbose_name='بدنه یا متن'),
        ),
    ]
