# Generated by Django 4.2.6 on 2023-11-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0007_articlesmodel_is_special_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='آدرس آی پی')),
            ],
        ),
        migrations.AddField(
            model_name='articlesmodel',
            name='hits',
            field=models.ManyToManyField(blank=True, related_name='hits', to='Articles.ipaddress', verbose_name='بازدید ها'),
        ),
    ]
