# Generated by Django 4.2.6 on 2023-10-11 07:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookHomeModelMainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_BookHome', models.ImageField(upload_to='BookHome_image', verbose_name='عکس کتاب')),
                ('title_BookHome', models.CharField(max_length=200, verbose_name='نام کتاب به طور کامل')),
                ('slug_BookHome', models.SlugField(max_length=100, unique=True, verbose_name='آدرس کتاب')),
                ('Publication_name_BookHome', models.CharField(max_length=200, verbose_name='نام نشر')),
                ('publication_date_BookHome', models.CharField(max_length=200, verbose_name='تاریخ نشر')),
                ('Place_of_publication_BookHome', models.CharField(max_length=200, verbose_name='محل نشر')),
                ('name_of_the_printing_house_BookHome', models.CharField(max_length=200, verbose_name='نام چاپخانه')),
                ('Number_of_circulation_BookHome', models.CharField(max_length=200, verbose_name='تعداد تیراژ')),
                ('Publishedbook_BookHome', models.CharField(max_length=200, verbose_name='نوبت چاپ')),
                ('price_of_the_book_BookHome', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت کتاب')),
                ('name_of_the_translator_or_translators_BookHome', models.CharField(max_length=200, verbose_name='نام مترجم یا مترجمان')),
                ('description_BookHome', models.TextField(verbose_name='توضیحات کتاب')),
                ('publish_BookHome', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار کتاب')),
                ('created_BookHome', models.DateTimeField(auto_now_add=True, verbose_name='کتاب کی ایجاد شد؟')),
                ('updated_BookHome', models.DateTimeField(auto_now=True, verbose_name='کتاب کی آپدیت شد؟')),
                ('status_BookHome', models.CharField(choices=[('d', 'پیش نویس'), ('p', 'منتشر'), ('p', 'تعداد کتاب محدود'), ('f', 'کتاب موجود نیست'), ('n', 'حذف خواهد شد'), ('b', 'به زودی موجود خواهد شد'), ('r', 'به دلیل عمل نکردن به قوانین سایت رد شد')], default='d', max_length=1, verbose_name='  وضعیت انتشار کتاب')),
                ('BookHome_type_BookHome', models.CharField(choices=[('انواع کتاب بر اساس موضوع؛ انواع سبک کتاب', (('ban', 'دانشگاهی'), ('bao', 'آموزشی'), ('bab', 'فانتزی'), ('bac', 'ماجراجویی'), ('bad', 'عاشقانه '), ('bae', 'ترسناک'), ('baf', 'مهیج '), ('bag', 'علمی تخیلی'), ('bah', 'هنری'), ('bai', 'انگیزشی'), ('baj', 'طنز'), ('bak', 'کودکان'), ('bal', 'کتاب های زندگینامه'), ('bam', 'کتاب های سفرنامه')))], max_length=3, verbose_name=' نوع کتاب')),
                ('is_sale_BookHome', models.BooleanField(default=False, verbose_name='تخفیف ویژه')),
            ],
            options={
                'verbose_name': 'کتاب',
                'verbose_name_plural': 'کتاب ها',
            },
        ),
    ]
