# Generated by Django 4.2.6 on 2023-10-15 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0003_articlehomemodelmainpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlehomemodelmainpage',
            name='status_ArticleHome',
            field=models.CharField(choices=[('d', 'پیش نویس'), ('p', 'منتشر'), ('m', 'تعداد مقاله محدود'), ('f', 'مقاله موجود نیست'), ('n', 'حذف خواهد شد'), ('b', 'به زودی موجود خواهد شد'), ('r', 'به دلیل عمل نکردن به قوانین سایت رد شد')], default='d', max_length=1, verbose_name='  وضعیت انتشار مقاله'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_category', models.CharField(max_length=200, verbose_name='عنوان دسته بندی ')),
                ('slug_category', models.SlugField(max_length=100, unique=True, verbose_name='آدرس دسته بندی')),
                ('status_category', models.BooleanField(default=True, verbose_name='آیا نمایش داده شود؟')),
                ('position_category', models.IntegerField(verbose_name='پوزیشن')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='MainPage.category', verbose_name='دسته بندی والد | زیر دسته')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
                'ordering': ['parent__id', 'position_category'],
            },
        ),
        migrations.AddField(
            model_name='alertmodelmainpage',
            name='category_alert',
            field=models.ManyToManyField(related_name='alerts', to='MainPage.category', verbose_name='دسته بندی'),
        ),
    ]
