# Generated by Django 4.2.6 on 2023-10-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0004_alter_articlehomemodelmainpage_status_articlehome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlehomemodelmainpage',
            name='category_ArticleHome',
            field=models.ManyToManyField(related_name='articls', to='MainPage.category', verbose_name='دسته بندی'),
        ),
        migrations.AddField(
            model_name='bookhomemodelmainpage',
            name='category_BookHome',
            field=models.ManyToManyField(related_name='books', to='MainPage.category', verbose_name='دسته بندی'),
        ),
    ]
