# Generated by Django 4.2.6 on 2023-10-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0005_articlehomemodelmainpage_category_articlehome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookhomemodelmainpage',
            name='status_BookHome',
            field=models.CharField(choices=[('d', 'پیش نویس'), ('p', 'منتشر'), ('m', 'تعداد کتاب محدود'), ('f', 'کتاب موجود نیست'), ('n', 'حذف خواهد شد'), ('b', 'به زودی موجود خواهد شد'), ('r', 'به دلیل عمل نکردن به قوانین سایت رد شد')], default='d', max_length=1, verbose_name='  وضعیت انتشار کتاب'),
        ),
    ]
